workflows:
  android-webview-build:
    name: Android WebView Build
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
